language: java
sudo: required
dist: trusty

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
  sonarcloud:
    organization: "iqbrod-github"

services:
  - mysql
before_script:
  - mysql_upgrade -u root
  - mysql -u root < sql_scripts/1.sql
  - mysql -u root -e "CREATE USER 'travisUser'@'localhost' IDENTIFIED BY 'travis';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travisUser'@'localhost' WITH GRANT OPTION;"
  - mysql -u root -e "FLUSH PRIVILEGES;"
  - mysql -u root --database=computer-database-db < sql_scripts/3.sql

script:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar
