ignore:
  - "core/src/main/java/com/excilys/cdb/enums/*"
  - "core/src/main/java/com/excilys/cdb/model/*"
  - "console/src/main/java/com/excilys/cdb/front_cli/*"
  - "binding/src/main/java/com/excilys/cdb/dto/*"
  - "webapp/*"

coverage:
  range: 50..75
  round: up
  status:
    project: off
    patch: off
