ignore:
  - "src/main/java/com/excilys/cdb/enums/*"
  - "src/main/java/com/excilys/cdb/model/*"
  - "src/main/java/com/excilys/cdb/userinterface/*"
  - "src/main/java/com/excilys/cdb/main/*"
  - "src/main/java/com/excilys/cdb/dto/*"

coverage:
  range: 50..75
  round: up
